### PR TITLE
Four, minor, typo edits

### PR DESCRIPTION
**Pull request by aczarnowski**
Changes for a few typos which I noted during my initial read.

The second is hard to see in the diff:

_For a moment **is** seemed -> For a moment **it** seemed_

The third may also be hard to see in the diff:

_schooldays -> school days_

which I believe meets SE's spelling modernization guidelines.

### CODE REVIEW

**Comment by acabal** [comment]
Hi there, thanks for proofing this!

For your change in The Final Problem, did you confirm that change in the source scans?

I don't think we should change "an Havana" to "a Havana" as it is dialectical speech. It is common for some English accents to not voice a leading H, thus they would use "an". For example "An hundred" is common in some English accents. Can you undo that edit?

**Comment by aczarnowski** [comment]
The original SE texts were true to the scans.  I've reverted the changes you mentioned, leaving only the two very minor edits outlined in the initial pull request.

Obviously, I'm still getting a feel for the SE guidelines around readability changes. Thanks for taking at look at these.

**Comment by acabal** [comment]
Great, thanks. Before I merge I want to ask you to clean up the commit history a little. For commits in which we make editorial changes, like "schooldays" -> "school days", please make those in a single commit whose message is prefaced with: `[Editorial]`. 

The typo fix can go in its own commit with any message you like, usually something simple like `Fix typo`.

You can do this on this branch with `git rebase` but that may be a little complex if you've never done it before. Since these changes are so small it might be easier to just do them on a fresh branch and make a new pull request. Either way works fine, whatever is easier for you.

Once we get that wrapped up I'll merge this right away.

**Comment by aczarnowski** [comment]
I tried a <code>rebase</code> and individual commits with the suggested messages.  Hopefully this is better rather than worse.

**Comment by acabal** [comment]
Excellent, thanks for your hard work!

**Comment by aczarnowski** [comment]
Well, the harder work was helping me through the process for a couple characters.  Thanks for that and for bringing these texts up to a great standard.

**Pull request merged**
