### PR TITLE
Fix missing word.

### PR DESCRIPTION
**Pull request by agl**

### CODE REVIEW

**Comment by agl** [comment]
Note that this error appears to be in the original:

image

However, I cannot see that it can be anything but an error so still think it worth correcting.

**Comment by acabal** [comment]
Interesting; I wonder why this kind of typo would have survived so many printings of such a popular book. Is this some kind of rare but acceptable grammar style in en-GB? @drgrigg thoughts?

**Comment by agl** [comment]
Perhaps this was an acceptable form at the time? There are a few examples in Google Books: [1](https://books.google.com/books?id=nL8TAAAAYAAJ&pg=PA13&dq=%22was+next+the%22&hl=en&sa=X&ved=0ahUKEwjRzPqKiubdAhXBhywKHZrFAcYQ6AEIRjAF#v=onepage&q=%22was%20next%20the%22&f=false) [2](https://books.google.com/books?id=ttWMEwYBJGoC&pg=PP462&dq=%22was+next+the%22&hl=en&sa=X&ved=0ahUKEwjRzPqKiubdAhXBhywKHZrFAcYQ6AEIMDAB#v=onepage&q=%22was%20next%20the%22&f=false) [3](https://books.google.com/books?id=a9deAAAAcAAJ&pg=PA402&dq=%22was+next+the%22&hl=en&sa=X&ved=0ahUKEwjRzPqKiubdAhXBhywKHZrFAcYQ6AEIWzAI#v=onepage&q=%22was%20next%20the%22&f=false).

**Comment by acabal** [comment]
Yeah if we're finding it in other texts from roughly the same time period then we can probably call it a rare style choice. Let's leave it for now unless we can find better evidence that it's actually a typo. Thanks for reporting though!

**Pull request closed without merging**
